# Generated by Django 5.1.1 on 2024-10-19 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('851ecc87-3a8b-4d18-af84-531a1265dc3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('851ecc87-3a8b-4d18-af84-531a1265dc3b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
