# Generated by Django 5.1.1 on 2024-10-19 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_alter_category_uid_alter_product_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ef84bad4-4b39-41de-9aa2-712c9ffe5f7f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ef84bad4-4b39-41de-9aa2-712c9ffe5f7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
