# Generated by Django 5.1.1 on 2024-10-19 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d3e35704-9e41-4961-be57-df45f95e82d5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d3e35704-9e41-4961-be57-df45f95e82d5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d3e35704-9e41-4961-be57-df45f95e82d5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
