# Generated by Django 5.1.1 on 2024-10-19 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cart_uid_alter_cartitems_uid_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0b4fafc2-09e0-416b-8e80-d9354e23424d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0b4fafc2-09e0-416b-8e80-d9354e23424d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0b4fafc2-09e0-416b-8e80-d9354e23424d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
